### ISSUE TITLE
Highlight icon on mouse hover

### ISSUE THREAD

**Issue by mike10004** [mike10004/gnome3-extensions#1]
Currently, other buttons on the panel are highlighted on mouseover, but our logout button is not. Like the other buttons, the foreground of the logout button should become a brighter shade of gray when the mouse cursor hovers over it and then revert to its original color when the mouse cursor leaves.

A tooltip that says "Log out" would also be helpful.

**Comment by l300lvl** [comment]
@mike10004 ive updated one of my extensions based on this and wanted to credit you, perhaps some things ive done can help you as well: https://github.com/l300lvl/Show-Desktop-Button/commit/5a23b2ff81dfc02eef3cf41452ae741ffaa73083

as far as your tooltip goes i plan to do this soon using this:

https://github.com/meghprkh/wintitle

**Comment by mike10004** [comment]
Thanks -- also thanks for reminding me that I can merge this
